import type { Metadata } from 'next'
import { Montserrat, Roboto_Condensed, Neuton } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Navigation from './components/Navigation'

const montserrat = Neuton({ subsets: ['latin'], weight: ['400']})
const robotoCondensed = Roboto_Condensed({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
